<?php
/*
Plugin Name: My Installed Android Apps
Plugin URI:  http://www.rawapps.com
Description: This plugin from RawApps.com makes it easy for you to share your list of installed Android apps in just a few simple steps. App lists are auto-generated by first syncing your device with RawApps Mobile. The plugin allows you to display your installed apps lists with a variety of features such as displaying the app thumbnail, application name, developer and category by default.The settings panel gives publishers additional options to show or hide app descriptions, app ratings, number of ratings and number of downloads through the settings panel.
Version: 0.5
Author: RawApps.com
Author URI: http://www.rawapps.com
*/

//  Adding Action
add_action('plugins_loaded','my_android_apps_display_widget');

//  Display Widget
function my_android_apps_display_widget() {
    register_sidebar_widget(__('My Installed Android Apps Widget'),'my_android_apps_widget');
    register_widget_control('My Installed Android Apps Widget','my_android_apps_widget_options');

}
//  Creating RawApps  widget
function my_android_apps_widget($args) {
    extract($args);
    $options=get_option("my_android_apps_widget");
    if (!is_array($options)) {
	    $options=array(
		    'title'=>'My Installed Android Apps',
		    'email'=> '',
		    'sort' =>'name',
		    'limit'=> '10',
		    'show_description'=>'1',
		    'show_credit'=>'1',
		    'show_ratings'=>'1',
		    'show_noratings'=>'1',
		    'show_star'=>'1',
		    'show_downloads'=>'1'
		    );

	}

    echo $before_widget;


    echo $before_title.$options['title'].$after_title;

    my_android_apps_widget_template();
    echo $after_widget;



}

   //   Widget template
   function my_android_apps_widget_template() {include_once(WP_PLUGIN_DIR."/my-installed-android-apps/rawapps_widget_template.php");}
   //   Widget Control Panel
    function my_android_apps_widget_options()
    {

	$options=get_option("my_android_apps_widget");
	if (!is_array($options)) {
	    $options=array(
		    'title'=>'My Installed Android Apps',
		    'email'=>'',
		    'sort' =>'name',
		    'limit'=> '10',
		    'show_description'=>'1',
		    'show_credit'=>'1',
		    'show_ratings'=>'1',
		    'show_noratings'=>'1',
		    'show_star'=>'1',
		    'show_downloads'=>'1'
		    );

	}
	if ($_POST['my-android-apps-widget-submit']) {
	    $options['title']=$_POST['widget_title'];
	    $options['email']=$_POST['widget_email'];
	    $options['sort'] =$_POST['widget_sort'];
	    $options['limit']=$_POST['widget_limit'];

	    if (isset($_POST['widget_show_description'])){
		    $options['show_description']=true;
	    }
	    else
	    {
		    $options['show_description']=false;
	    }
	    if (isset($_POST['widget_show_ratings'])){
		    $options['show_ratings']=true;
	    }
	    else
	    {
		    $options['show_ratings']=false;
	    }
	    if (isset($_POST['widget_show_noratings'])){
		    $options['show_noratings']=true;
	    }
	    else
	    {
		    $options['show_noratings']=false;
	    }
	    if (isset($_POST['widget_show_downloads'])){
		    $options['show_downloads']=true;
	    }
	    else
	    {
		    $options['show_downloads']=false;
	    }
	    if (isset($_POST['widget_show_credit'])){
		    $options['show_credit']=true;
	    }
	    else
	    {
		    $options['show_credit']=false;
	    }
	    if (isset($_POST['widget_show_star'])){
		    $options['show_star']=true;
	    }
	    else
	    {
		    $options['show_star']=false;
	    }



	    update_option("my_android_apps_widget",$options);
	}
	//Form
	echo "<label for='rawapps_widget_title'> "._e('Title') .": </label>";
	echo "<input style='width:175px;margin-left:8px;' type='text' name='widget_title' value='".$options['title']."' /><br/>";
	echo "<label for='rawapps_widget_title'> "._e('Email') .": </label>";
	echo "<input style='width:175px;' type='text' name='widget_email' value='".$options['email']."' /><br/>";
	echo "<label style= 'color:silver;padding-left:2px;' for='rawapps_widget_title'> To sync, enter the same email you used to register on RawApps.com </label/><br/>";

	$is_checked = "";
	if ($options['show_description']){
		$is_checked = "checked";
	}
	echo "<input type='checkbox' name='widget_show_description' value='1' ".$is_checked."/> Description  ";

		$showdownloads = "";
	if ($options['show_downloads']){
		$showdownloads = "checked";
	}
	echo "<input style='margin-left:20px'  type='checkbox' name='widget_show_downloads' value='1' ".$showdownloads."/> No. Downloads<br/> ";


	$showratings = "";
	if ($options['show_ratings']){
		$showratings = "checked";
	}
	echo "<input type='checkbox' name='widget_show_ratings' value='1' ".$showratings."/> <label style='padding-right:22px'>Ratings</label>  ";

	$shownoratings = "";
	if ($options['show_noratings']){
		$shownoratings = "checked";
	}
	echo "<input style='margin-left:20px'  type='checkbox' name='widget_show_noratings' value='1' ".$shownoratings."/> No. Ratings <br/>";

	$showstar = "";
	if ($options['show_star']){
		$showstar = "checked";
	}
	echo "<input type='checkbox' name='widget_show_star' value='1' ".$showstar."/> <label style='padding-right:22px'> Stars</label>  ";



	$showcredit = "";
	if ($options['show_credit']){
		$showcredit = "checked";
	}
	echo "<input style='margin-left:32px'  type='checkbox' name='widget_show_credit' value='1' ".$showcredit."/> <label>Credits</label> <br/> ";


	echo "<label for='rawapps_widget_title'>Sort</label/>";
	?>
	<select style='width:175px;margin-left:20px' name='widget_sort'>
		<option value='author'<?php if ($options['sort']=='author') {echo " selected='selected'";} ?>><?php _e('Author'); ?></option>
		<option value='name'  <?php if ($options['sort']=='name')   {echo " selected='selected'";} ?>><?php _e('Name');   ?></option>
		<option value='rating'<?php if ($options['sort']=='rating') {echo " selected='selected'";} ?>><?php _e('Rating'); ?></option>
	</select><br/>
	<?php

	echo "<label for='rawapps_widget_limit'> "._e('No. Apps') .": </label>";
	echo "<input style='width:160px;' type='text' name='widget_limit' value='".$options['limit']."' /><br/>";




	echo "<input type='hidden' id='my-android-apps-widget-submit' name='my-android-apps-widget-submit' value='1' />";




    }


?>
